[package]
name = "femto"
version = "0.0.2"
authors = ["senees <code@senees.de>"]
description = "femto"
documentation = "https://docs.rs/femto"
repository = "https://github.com/senees/femto.git"
license = "MIT"
edition = "2021"