[package]
name = "femto"
version = "0.0.3"
authors = ["Dariusz Depta <depta@senees.de>"]
description = "femto"
documentation = "https://docs.rs/femto"
repository = "https://github.com/senees/femto.git"
license = "MIT"
edition = "2021"